### ISSUE TITLE
rosey.exe is not generated

### ISSUE THREAD

**Issue by michael-proulx** [CloudCannon/rosey#58]
After seeing the blog post on CloudCannon about Astro + Rosey, I wanted to try it out.
There is no error message when executing `npx rosey generate --source dist`.

I took a look at the `node_modules`, and I noticed that you're purposefully ignoring errors in the try-catch block for `execFileSync`. So, I added a `console.error(err)`.

Here is the error output:
```node
code: 'ENOENT',
syscall: 'spawnSync C:\\dev\\git\\11ty-rosey\\node_modules\\rosey\\bin\\rosey.exe',
path: 'C:\\dev\\git\\11ty-rosey\\node_modules\\rosey\\bin\\rosey.exe',
spawnargs: [ 'generate', '--source', 'dist' ],
error: [Circular *1],
```

It appears that on Windows, `../bin/rosey.exe` doesn't exist.

![image](https://github.com/user-attachments/assets/f5f9212d-72e4-44fa-b97a-6f92cc01b39f)

**Comment by michael-proulx** [comment]
After more testing and debugging, I found that renaming `bin/rosey` to `bin/rosey.exe` fixes everything. Upon further inspection, I noticed that you're unzipping `rosey-v2.1.0-x86_64-pc-windows-msvc.tar.gz`, but the `.tar.gz` file doesn't contain the `.exe` file.

**Comment by bglw** [comment]
Hey @michael-proulx — good catch! It looks like the wrapper and release action have gotten a little out of sync with each other for Windows, sorry about that.

I'll update the action to correctly add the `.exe` and trigger a new release.

**Comment by bglw** [comment]
Hey @michael-proulx 👋 

Rosey 2.1.1 has been released and contains a fix for this issue on Windows. Let me know if you see any further issues running it 🙂

**Comment by michael-proulx** [comment]
Hey @bglw 

Everything works 😊

Thanks!
