### ISSUE TITLE
[Feature] Origin URLs remain the same

### ISSUE THREAD

**Issue by michael-proulx** [CloudCannon/rosey#59]
I would like the URLs to remain the same as the original.

For example:
- `/en/` should be `/`
- `/en/about/` should be `/about/`

I don't need a redirect page.

In my project, I could use the original source and only copy the localized output or use redirects. However, the canonical links in the localized sources will have the incorrect original URL, or this approach will cause excessive redirects on our website for no reason.

**Comment by bglw** [comment]
Hey @michael-proulx 👋 

This has been implemented and released in Rosey 2.2.0 🎉 

This behavior can be achieved by passing the flag `--default-language-at-root` to Rosey's build command. Documentation for the new flag: https://rosey.app/docs/build/#default-language-at-root

Let me know if you give this a go and whether it works for your needs 🙂

**Comment by michael-proulx** [comment]
Hey @bglw

Woah! I wasn't expecting that one to be done so fast!
This is working very well!

I was wondering if you have any thoughts about markdown, I know that we can do `data-rosey="content"` and it will output the full HTML, but what about custom snippets into markdown?

I thought about customizing the markdown renderer to add `data-rosey` to all elements, but I'm not sure if that's the best idea.

Thanks!

**Comment by michael-proulx** [comment]
Perfect, I'll do some testing. Since we're using your CMS, I think I could try creating a custom snippet for translation that will recognize those custom snippets.
