### ISSUE TITLE
[Feature] checks.json default sorting

### ISSUE THREAD

**Issue by michael-proulx** [CloudCannon/rosey#62]
Since we are commiting the checks.json for our CloudCannon translation.

We would like to have default sorting for `states` and `keys` to prevent file change.

![image](https://github.com/user-attachments/assets/f1fe85dc-7bc7-444c-8b01-b892776977ad)

**Comment by bglw** [comment]
Hey @michael-proulx 👋 

This was a very simple tweak so I've shipped it out as [Rosey v2.2.1](https://github.com/CloudCannon/rosey/releases/tag/v2.2.1) 🙂

**Comment by michael-proulx** [comment]
🥳 Thanks!
